FROM ubuntu:latest
MAINTAINER Choi_Jihyoun "jihyoun0403@gmail.com"
RUN apt-get -y update
RUN apt-get -y install python
RUN apt-get -y install python-pip
COPY . /app
WORKDIR /app
RUN pip install -r requirements2.txt
ENTRYPOINT ["python"]
CMD ["app.py"]